theme: jekyll-theme-minimal
title: Boris Podolnyi
description: """
# Hi, I’m obopodo! \nSound Artist, Musician, Composer, Data Scientist, and former Biophysicist trying to blend all these fields together
"""
